language: ruby
rvm:
  - 1.9.3
env:
  - "RAILS_ENV=test DB=mysql2 BUNDLE_WITHOUT=rmagick:mysql:postgres:sqlite"
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get --no-install-recommends install bzr cvs git mercurial subversion"
before_script:
  - "rvm rubygems 1.8.25" # Rubygems 2.0.x fails with Rails 2.3
  - "rake ci:travis:prepare"
  - "rm -rf tmp/test/darcs_repository" # Don't test Darcs on Travis. It breaks there :(
branches:
  only:
    - stable
notifications:
  email: false
