production:
  adapter: mysql2
  database: chiliproject
  host: localhost
  username: root
  password:
  encoding: utf8
 
development:
  adapter: mysql2
  database: chiliproject_development
  host: localhost
  username: root
  password:
  encoding: utf8
